/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zikri
 */
public class menuDashboard extends javax.swing.JPanel {

    /**
     * Creates new form menuDashboard
     */
    public menuDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CPeminjam = new javax.swing.JPanel();
        TPeminjaman = new javax.swing.JLabel();
        LPeminjam = new javax.swing.JLabel();
        JPeminjam = new javax.swing.JLabel();
        CBuku = new javax.swing.JPanel();
        TBuku = new javax.swing.JLabel();
        LBuku = new javax.swing.JLabel();
        JBuku = new javax.swing.JLabel();
        CAnggota2 = new javax.swing.JPanel();
        TAnggota2 = new javax.swing.JLabel();
        LAnggota2 = new javax.swing.JLabel();
        JAnggota2 = new javax.swing.JLabel();
        CPengembalian = new javax.swing.JPanel();
        TPengembalian = new javax.swing.JLabel();
        LPengembalian = new javax.swing.JLabel();
        JPengembalian = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPeminjam = new javax.swing.JTable();
        SDaschboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LDashboard = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(941, 531));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CPeminjam.setBackground(new java.awt.Color(0, 204, 204));

        TPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        TPeminjaman.setText("Peminjaman");

        LPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        LPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reading-book.png"))); // NOI18N

        JPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        JPeminjam.setText("000");

        javax.swing.GroupLayout CPeminjamLayout = new javax.swing.GroupLayout(CPeminjam);
        CPeminjam.setLayout(CPeminjamLayout);
        CPeminjamLayout.setHorizontalGroup(
            CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPeminjamLayout.createSequentialGroup()
                .addGroup(CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JPeminjam))
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TPeminjaman)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LPeminjam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CPeminjamLayout.setVerticalGroup(
            CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPeminjamLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LPeminjam)
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addComponent(TPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPeminjam)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        TPeminjaman.getAccessibleContext().setAccessibleName("TAnggota");
        LPeminjam.getAccessibleContext().setAccessibleName("");

        jPanel1.add(CPeminjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 180, 100));

        CBuku.setBackground(new java.awt.Color(0, 204, 204));

        TBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TBuku.setForeground(new java.awt.Color(255, 255, 255));
        TBuku.setText("Buku");

        LBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBuku.setForeground(new java.awt.Color(255, 255, 255));
        LBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (5).png"))); // NOI18N

        JBuku.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JBuku.setForeground(new java.awt.Color(255, 255, 255));
        JBuku.setText("000");

        javax.swing.GroupLayout CBukuLayout = new javax.swing.GroupLayout(CBuku);
        CBuku.setLayout(CBukuLayout);
        CBukuLayout.setHorizontalGroup(
            CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBukuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CBukuLayout.createSequentialGroup()
                        .addComponent(JBuku)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CBukuLayout.createSequentialGroup()
                        .addComponent(TBuku)
                        .addGap(26, 26, 26)))
                .addComponent(LBuku)
                .addContainerGap())
        );
        CBukuLayout.setVerticalGroup(
            CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBuku)
                    .addGroup(CBukuLayout.createSequentialGroup()
                        .addComponent(TBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBuku)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(CBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 170, -1));

        CAnggota2.setBackground(new java.awt.Color(0, 204, 204));

        TAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        TAnggota2.setText("Anggota");

        LAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        LAnggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group (1).png"))); // NOI18N

        JAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        JAnggota2.setText("000");

        javax.swing.GroupLayout CAnggota2Layout = new javax.swing.GroupLayout(CAnggota2);
        CAnggota2.setLayout(CAnggota2Layout);
        CAnggota2Layout.setHorizontalGroup(
            CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAnggota2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAnggota2)
                    .addGroup(CAnggota2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JAnggota2)))
                .addGap(18, 18, 18)
                .addComponent(LAnggota2)
                .addGap(37, 37, 37))
        );
        CAnggota2Layout.setVerticalGroup(
            CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAnggota2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LAnggota2)
                    .addGroup(CAnggota2Layout.createSequentialGroup()
                        .addComponent(TAnggota2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JAnggota2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(CAnggota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 100));

        CPengembalian.setBackground(new java.awt.Color(0, 204, 204));

        TPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        TPengembalian.setText("Pengembalian");

        LPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        LPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (3).png"))); // NOI18N

        JPengembalian.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JPengembalian.setForeground(new java.awt.Color(255, 255, 255));
        JPengembalian.setText("000");

        javax.swing.GroupLayout CPengembalianLayout = new javax.swing.GroupLayout(CPengembalian);
        CPengembalian.setLayout(CPengembalianLayout);
        CPengembalianLayout.setHorizontalGroup(
            CPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPengembalianLayout.createSequentialGroup()
                .addGroup(CPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPengembalianLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(JPengembalian))
                    .addGroup(CPengembalianLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TPengembalian)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LPengembalian)
                .addGap(37, 37, 37))
        );
        CPengembalianLayout.setVerticalGroup(
            CPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CPengembalianLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(CPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LPengembalian)
                    .addGroup(CPengembalianLayout.createSequentialGroup()
                        .addComponent(TPengembalian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPengembalian)))
                .addGap(14, 14, 14))
        );

        jPanel1.add(CPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 90, 180, 100));

        TbPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbPeminjam);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 900, 260));

        SDaschboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SDaschboard.setForeground(new java.awt.Color(102, 102, 102));
        SDaschboard.setText("Master Data > Dashboard");
        jPanel1.add(SDaschboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Riwayat Peminjaman Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        LDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desktop.png"))); // NOI18N
        jPanel1.add(LDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 532, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CAnggota2;
    private javax.swing.JPanel CBuku;
    private javax.swing.JPanel CPeminjam;
    private javax.swing.JPanel CPengembalian;
    private javax.swing.JLabel JAnggota2;
    private javax.swing.JLabel JBuku;
    private javax.swing.JLabel JPeminjam;
    private javax.swing.JLabel JPengembalian;
    private javax.swing.JLabel LAnggota2;
    private javax.swing.JLabel LBuku;
    private javax.swing.JLabel LDashboard;
    private javax.swing.JLabel LPeminjam;
    private javax.swing.JLabel LPengembalian;
    private javax.swing.JLabel SDaschboard;
    private javax.swing.JLabel TAnggota2;
    private javax.swing.JLabel TBuku;
    private javax.swing.JLabel TPeminjaman;
    private javax.swing.JLabel TPengembalian;
    private javax.swing.JTable TbPeminjam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
