/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zikri
 */
public class menuBuku extends javax.swing.JPanel {

    /**
     * Creates new form menuBuku
     */
    public menuBuku() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CBuku = new javax.swing.JPanel();
        TBuku = new javax.swing.JLabel();
        LBuku = new javax.swing.JLabel();
        JBuku = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPeminjam = new javax.swing.JTable();
        SDaschboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LDashboard = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(940, 530));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CBuku.setBackground(new java.awt.Color(0, 204, 204));

        TBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TBuku.setForeground(new java.awt.Color(255, 255, 255));
        TBuku.setText("Buku");

        LBuku.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBuku.setForeground(new java.awt.Color(255, 255, 255));
        LBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (5).png"))); // NOI18N

        JBuku.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JBuku.setForeground(new java.awt.Color(255, 255, 255));
        JBuku.setText("000");

        javax.swing.GroupLayout CBukuLayout = new javax.swing.GroupLayout(CBuku);
        CBuku.setLayout(CBukuLayout);
        CBukuLayout.setHorizontalGroup(
            CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBukuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CBukuLayout.createSequentialGroup()
                        .addComponent(JBuku)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CBukuLayout.createSequentialGroup()
                        .addComponent(TBuku)
                        .addGap(26, 26, 26)))
                .addComponent(LBuku)
                .addContainerGap())
        );
        CBukuLayout.setVerticalGroup(
            CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LBuku)
                    .addGroup(CBukuLayout.createSequentialGroup()
                        .addComponent(TBuku)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JBuku)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(CBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, -1));

        TbPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbPeminjam);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 900, 260));

        SDaschboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SDaschboard.setForeground(new java.awt.Color(102, 102, 102));
        SDaschboard.setText("Master Data > Buku");
        jPanel1.add(SDaschboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Daftar Buku");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        LDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LBuku(2).png"))); // NOI18N
        jPanel1.add(LDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CBuku;
    private javax.swing.JLabel JBuku;
    private javax.swing.JLabel LBuku;
    private javax.swing.JLabel LDashboard;
    private javax.swing.JLabel SDaschboard;
    private javax.swing.JLabel TBuku;
    private javax.swing.JTable TbPeminjam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
