/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zikri
 */
public class menuAnggota extends javax.swing.JPanel {

    /**
     * Creates new form menuAnggota
     */
    public menuAnggota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CAnggota2 = new javax.swing.JPanel();
        TAnggota2 = new javax.swing.JLabel();
        LAnggota2 = new javax.swing.JLabel();
        JAnggota2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPeminjam = new javax.swing.JTable();
        SDaschboard = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LDashboard = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(940, 530));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CAnggota2.setBackground(new java.awt.Color(0, 204, 204));

        TAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        TAnggota2.setText("Anggota");

        LAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        LAnggota2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group (1).png"))); // NOI18N

        JAnggota2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JAnggota2.setForeground(new java.awt.Color(255, 255, 255));
        JAnggota2.setText("000");

        javax.swing.GroupLayout CAnggota2Layout = new javax.swing.GroupLayout(CAnggota2);
        CAnggota2.setLayout(CAnggota2Layout);
        CAnggota2Layout.setHorizontalGroup(
            CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAnggota2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TAnggota2)
                    .addGroup(CAnggota2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(JAnggota2)))
                .addGap(18, 18, 18)
                .addComponent(LAnggota2)
                .addGap(37, 37, 37))
        );
        CAnggota2Layout.setVerticalGroup(
            CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CAnggota2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CAnggota2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LAnggota2)
                    .addGroup(CAnggota2Layout.createSequentialGroup()
                        .addComponent(TAnggota2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JAnggota2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.add(CAnggota2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 170, 100));

        TbPeminjam.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TbPeminjam);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 900, 260));

        SDaschboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SDaschboard.setForeground(new java.awt.Color(102, 102, 102));
        SDaschboard.setText("Master Data > Anggota");
        jPanel2.add(SDaschboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Daftar Anggota");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        LDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/LAnggota(2).png"))); // NOI18N
        jPanel2.add(LDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CAnggota2;
    private javax.swing.JLabel JAnggota2;
    private javax.swing.JLabel LAnggota2;
    private javax.swing.JLabel LDashboard;
    private javax.swing.JLabel SDaschboard;
    private javax.swing.JLabel TAnggota2;
    private javax.swing.JTable TbPeminjam;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
