/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

/**
 *
 * @author zikri
 */
public class menuLPeminjaman extends javax.swing.JPanel {

    /**
     * Creates new form menuLPeminjaman
     */
    public menuLPeminjaman() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CPeminjam = new javax.swing.JPanel();
        TPeminjaman = new javax.swing.JLabel();
        LPeminjam = new javax.swing.JLabel();
        JPeminjam = new javax.swing.JLabel();

        CPeminjam.setBackground(new java.awt.Color(0, 204, 204));

        TPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TPeminjaman.setForeground(new java.awt.Color(255, 255, 255));
        TPeminjaman.setText("Peminjaman");

        LPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        LPeminjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reading-book.png"))); // NOI18N

        JPeminjam.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JPeminjam.setForeground(new java.awt.Color(255, 255, 255));
        JPeminjam.setText("000");

        javax.swing.GroupLayout CPeminjamLayout = new javax.swing.GroupLayout(CPeminjam);
        CPeminjam.setLayout(CPeminjamLayout);
        CPeminjamLayout.setHorizontalGroup(
            CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPeminjamLayout.createSequentialGroup()
                .addGroup(CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(JPeminjam))
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TPeminjaman)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LPeminjam)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        CPeminjamLayout.setVerticalGroup(
            CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CPeminjamLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(CPeminjamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(LPeminjam)
                    .addGroup(CPeminjamLayout.createSequentialGroup()
                        .addComponent(TPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JPeminjam)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        setLayout(new java.awt.CardLayout());
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CPeminjam;
    private javax.swing.JLabel JPeminjam;
    private javax.swing.JLabel LPeminjam;
    private javax.swing.JLabel TPeminjaman;
    // End of variables declaration//GEN-END:variables
}
