/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package perpustakaan;

import java.awt.Color;
import view.menuDashboard;

/**
 *
 * @author zikri
 */
public class Futama extends javax.swing.JFrame {
    
    int xx,xy;
    /**
     * Creates new form Futama
     */
    public Futama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        LPerpus = new javax.swing.JLabel();
        TPerpus = new javax.swing.JLabel();
        TMD1 = new javax.swing.JLabel();
        PnBuku = new javax.swing.JPanel();
        PnLine3 = new javax.swing.JPanel();
        LBuku = new javax.swing.JLabel();
        btn_Buku = new javax.swing.JLabel();
        PnAnggota = new javax.swing.JPanel();
        PnLine2 = new javax.swing.JPanel();
        LAnggota = new javax.swing.JLabel();
        btn_Anggota = new javax.swing.JLabel();
        PnAdmin = new javax.swing.JPanel();
        PnLine4 = new javax.swing.JPanel();
        LAdmin = new javax.swing.JLabel();
        btn_Admin = new javax.swing.JLabel();
        TMD2 = new javax.swing.JLabel();
        PnPeminjaman = new javax.swing.JPanel();
        PnLine5 = new javax.swing.JPanel();
        LPeminjaman = new javax.swing.JLabel();
        btn_Peminjaman = new javax.swing.JLabel();
        PnPengembalian = new javax.swing.JPanel();
        PnLine6 = new javax.swing.JPanel();
        LPengembalian = new javax.swing.JLabel();
        btn_Pengembalian = new javax.swing.JLabel();
        TMD = new javax.swing.JLabel();
        PnLPeminjaman = new javax.swing.JPanel();
        PnLine7 = new javax.swing.JPanel();
        LLPeminjaman = new javax.swing.JLabel();
        btn_LPeminjaman = new javax.swing.JLabel();
        PnDashboard = new javax.swing.JPanel();
        PnLine1 = new javax.swing.JPanel();
        LDashboard = new javax.swing.JLabel();
        btn_dashboard = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Nav = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        PnUtama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LPerpus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LPerpus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LPerpus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (2).png"))); // NOI18N
        LPerpus.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(LPerpus, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 79, 70));

        TPerpus.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TPerpus.setText("Perpustakaan");
        jPanel2.add(TPerpus, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 48, -1, -1));

        TMD1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TMD1.setForeground(new java.awt.Color(102, 102, 102));
        TMD1.setText("Master Data");
        jPanel2.add(TMD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 108, -1, -1));

        PnBuku.setBackground(new java.awt.Color(255, 255, 255));

        PnLine3.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine3Layout = new javax.swing.GroupLayout(PnLine3);
        PnLine3.setLayout(PnLine3Layout);
        PnLine3Layout.setHorizontalGroup(
            PnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine3Layout.setVerticalGroup(
            PnLine3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 44, Short.MAX_VALUE)
        );

        LBuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (6).png"))); // NOI18N

        btn_Buku.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Buku.setText("Buku");
        btn_Buku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_BukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_BukuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_BukuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnBukuLayout = new javax.swing.GroupLayout(PnBuku);
        PnBuku.setLayout(PnBukuLayout);
        PnBukuLayout.setHorizontalGroup(
            PnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBukuLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LBuku, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Buku, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnBukuLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        PnBukuLayout.setVerticalGroup(
            PnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBukuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LBuku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Buku, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnBukuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        PnAnggota.setBackground(new java.awt.Color(255, 255, 255));

        PnLine2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine2Layout = new javax.swing.GroupLayout(PnLine2);
        PnLine2.setLayout(PnLine2Layout);
        PnLine2Layout.setHorizontalGroup(
            PnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine2Layout.setVerticalGroup(
            PnLine2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/group (2).png"))); // NOI18N

        btn_Anggota.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Anggota.setText("Anggota");
        btn_Anggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AnggotaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AnggotaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AnggotaMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnAnggotaLayout = new javax.swing.GroupLayout(PnAnggota);
        PnAnggota.setLayout(PnAnggotaLayout);
        PnAnggotaLayout.setHorizontalGroup(
            PnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAnggotaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Anggota, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnAnggotaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        PnAnggotaLayout.setVerticalGroup(
            PnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAnggotaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_Anggota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnAnggotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnAnggota, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, 50));

        PnAdmin.setBackground(new java.awt.Color(255, 255, 255));

        PnLine4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine4Layout = new javax.swing.GroupLayout(PnLine4);
        PnLine4.setLayout(PnLine4Layout);
        PnLine4Layout.setHorizontalGroup(
            PnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine4Layout.setVerticalGroup(
            PnLine4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/working (1).png"))); // NOI18N

        btn_Admin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Admin.setText("Admin");
        btn_Admin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_AdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_AdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_AdminMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnAdminLayout = new javax.swing.GroupLayout(PnAdmin);
        PnAdmin.setLayout(PnAdminLayout);
        PnAdminLayout.setHorizontalGroup(
            PnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAdminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, 140, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnAdminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(202, Short.MAX_VALUE)))
        );
        PnAdminLayout.setVerticalGroup(
            PnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnAdminLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_Admin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 220, 50));

        TMD2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TMD2.setForeground(new java.awt.Color(102, 102, 102));
        TMD2.setText("Transaksi");
        jPanel2.add(TMD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        PnPeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        PnLine5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine5Layout = new javax.swing.GroupLayout(PnLine5);
        PnLine5.setLayout(PnLine5Layout);
        PnLine5Layout.setHorizontalGroup(
            PnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine5Layout.setVerticalGroup(
            PnLine5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reading-book (1).png"))); // NOI18N

        btn_Peminjaman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Peminjaman.setText("Peminjaman");
        btn_Peminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PeminjamanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnPeminjamanLayout = new javax.swing.GroupLayout(PnPeminjaman);
        PnPeminjaman.setLayout(PnPeminjamanLayout);
        PnPeminjamanLayout.setHorizontalGroup(
            PnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPeminjamanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnPeminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        PnPeminjamanLayout.setVerticalGroup(
            PnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_Peminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, 50));

        PnPengembalian.setBackground(new java.awt.Color(255, 255, 255));

        PnLine6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine6Layout = new javax.swing.GroupLayout(PnLine6);
        PnLine6.setLayout(PnLine6Layout);
        PnLine6Layout.setHorizontalGroup(
            PnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine6Layout.setVerticalGroup(
            PnLine6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LPengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/book (4).png"))); // NOI18N

        btn_Pengembalian.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Pengembalian.setText("Pengembalian");
        btn_Pengembalian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_PengembalianMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_PengembalianMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_PengembalianMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnPengembalianLayout = new javax.swing.GroupLayout(PnPengembalian);
        PnPengembalian.setLayout(PnPengembalianLayout);
        PnPengembalianLayout.setHorizontalGroup(
            PnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPengembalianLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LPengembalian, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_Pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnPengembalianLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        PnPengembalianLayout.setVerticalGroup(
            PnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnPengembalianLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LPengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_Pengembalian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnPengembalianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, -1, 50));

        TMD.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TMD.setForeground(new java.awt.Color(102, 102, 102));
        TMD.setText("Laporan");
        jPanel2.add(TMD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        PnLPeminjaman.setBackground(new java.awt.Color(255, 255, 255));

        PnLine7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine7Layout = new javax.swing.GroupLayout(PnLine7);
        PnLine7.setLayout(PnLine7Layout);
        PnLine7Layout.setHorizontalGroup(
            PnLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine7Layout.setVerticalGroup(
            PnLine7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LLPeminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reading-book (1).png"))); // NOI18N

        btn_LPeminjaman.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_LPeminjaman.setText("Peminjaman");
        btn_LPeminjaman.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_LPeminjamanMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_LPeminjamanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_LPeminjamanMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnLPeminjamanLayout = new javax.swing.GroupLayout(PnLPeminjaman);
        PnLPeminjaman.setLayout(PnLPeminjamanLayout);
        PnLPeminjamanLayout.setHorizontalGroup(
            PnLPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnLPeminjamanLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LLPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_LPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnLPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnLPeminjamanLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(201, Short.MAX_VALUE)))
        );
        PnLPeminjamanLayout.setVerticalGroup(
            PnLPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnLPeminjamanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnLPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LLPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_LPeminjaman, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnLPeminjamanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnLPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, -1, 50));

        PnDashboard.setBackground(new java.awt.Color(255, 255, 255));

        PnLine1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PnLine1Layout = new javax.swing.GroupLayout(PnLine1);
        PnLine1.setLayout(PnLine1Layout);
        PnLine1Layout.setHorizontalGroup(
            PnLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 12, Short.MAX_VALUE)
        );
        PnLine1Layout.setVerticalGroup(
            PnLine1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        LDashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/desktop.png"))); // NOI18N

        btn_dashboard.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dashboard.setText("Dashboard");
        btn_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_dashboardMouseExited(evt);
            }
        });

        javax.swing.GroupLayout PnDashboardLayout = new javax.swing.GroupLayout(PnDashboard);
        PnDashboard.setLayout(PnDashboardLayout);
        PnDashboardLayout.setHorizontalGroup(
            PnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnDashboardLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(LDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(PnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(PnDashboardLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PnLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(182, Short.MAX_VALUE)))
        );
        PnDashboardLayout.setVerticalGroup(
            PnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnDashboardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LDashboard, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(btn_dashboard, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(PnDashboardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PnLine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(PnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 200, -1));

        jPanel7.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 670));

        jPanel3.setLayout(new java.awt.BorderLayout());

        Nav.setBackground(new java.awt.Color(0, 204, 204));
        Nav.setPreferredSize(new java.awt.Dimension(950, 100));

        javax.swing.GroupLayout NavLayout = new javax.swing.GroupLayout(Nav);
        Nav.setLayout(NavLayout);
        NavLayout.setHorizontalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 980, Short.MAX_VALUE)
        );
        NavLayout.setVerticalGroup(
            NavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jPanel3.add(Nav, java.awt.BorderLayout.PAGE_START);

        jPanel5.setLayout(new java.awt.BorderLayout());
        jPanel3.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel9.setBackground(new java.awt.Color(250, 250, 250));

        PnUtama.setBackground(new java.awt.Color(255, 255, 255));
        PnUtama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PnUtama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(PnUtama, javax.swing.GroupLayout.PREFERRED_SIZE, 532, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel7.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 980, 670));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_dashboardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseEntered
        // TODO add your handling code here:
        PnDashboard.setBackground(Color.white);
        PnLine1.setBackground(Color.blue);
    }//GEN-LAST:event_btn_dashboardMouseEntered

    private void btn_dashboardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseExited
        // TODO add your handling code here:
        PnDashboard.setBackground(Color.white);
        PnLine1.setBackground(Color.white);
    }//GEN-LAST:event_btn_dashboardMouseExited

    private void btn_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_dashboardMouseClicked
        // TODO add your handling code here:
        PnDashboard.setBackground(Color.GRAY);
        PnLine1.setBackground(Color.blue);
        
        PnUtama.removeAll();
        PnUtama.add(new menuDashboard());
        PnUtama.repaint();
        PnUtama.revalidate();
    }//GEN-LAST:event_btn_dashboardMouseClicked

    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        // TODO add your handling code here:
        xx = evt.getX();
        xy = evt.getY();             
    }//GEN-LAST:event_formMousePressed

    private void btn_AnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnggotaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnggotaMouseClicked

    private void btn_AnggotaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnggotaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnggotaMouseEntered

    private void btn_AnggotaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AnggotaMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AnggotaMouseExited

    private void btn_BukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BukuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BukuMouseClicked

    private void btn_BukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BukuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BukuMouseEntered

    private void btn_BukuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_BukuMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_BukuMouseExited

    private void btn_AdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AdminMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AdminMouseClicked

    private void btn_AdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AdminMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AdminMouseEntered

    private void btn_AdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_AdminMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_AdminMouseExited

    private void btn_PeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PeminjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PeminjamanMouseClicked

    private void btn_PeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PeminjamanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PeminjamanMouseEntered

    private void btn_PeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PeminjamanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PeminjamanMouseExited

    private void btn_PengembalianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PengembalianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PengembalianMouseClicked

    private void btn_PengembalianMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PengembalianMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PengembalianMouseEntered

    private void btn_PengembalianMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_PengembalianMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_PengembalianMouseExited

    private void btn_LPeminjamanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LPeminjamanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LPeminjamanMouseClicked

    private void btn_LPeminjamanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LPeminjamanMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LPeminjamanMouseEntered

    private void btn_LPeminjamanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_LPeminjamanMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_LPeminjamanMouseExited

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y -xy);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Futama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Futama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LAdmin;
    private javax.swing.JLabel LAnggota;
    private javax.swing.JLabel LBuku;
    private javax.swing.JLabel LDashboard;
    private javax.swing.JLabel LLPeminjaman;
    private javax.swing.JLabel LPeminjaman;
    private javax.swing.JLabel LPengembalian;
    private javax.swing.JLabel LPerpus;
    private javax.swing.JPanel Nav;
    private javax.swing.JPanel PnAdmin;
    private javax.swing.JPanel PnAnggota;
    private javax.swing.JPanel PnBuku;
    private javax.swing.JPanel PnDashboard;
    private javax.swing.JPanel PnLPeminjaman;
    private javax.swing.JPanel PnLine1;
    private javax.swing.JPanel PnLine2;
    private javax.swing.JPanel PnLine3;
    private javax.swing.JPanel PnLine4;
    private javax.swing.JPanel PnLine5;
    private javax.swing.JPanel PnLine6;
    private javax.swing.JPanel PnLine7;
    private javax.swing.JPanel PnPeminjaman;
    private javax.swing.JPanel PnPengembalian;
    private javax.swing.JPanel PnUtama;
    private javax.swing.JLabel TMD;
    private javax.swing.JLabel TMD1;
    private javax.swing.JLabel TMD2;
    private javax.swing.JLabel TPerpus;
    private javax.swing.JLabel btn_Admin;
    private javax.swing.JLabel btn_Anggota;
    private javax.swing.JLabel btn_Buku;
    private javax.swing.JLabel btn_LPeminjaman;
    private javax.swing.JLabel btn_Peminjaman;
    private javax.swing.JLabel btn_Pengembalian;
    private javax.swing.JLabel btn_dashboard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
